### ISSUE TITLE
Wait for bindgen to fix UB warning

### ISSUE THREAD

**Issue by mgeier** [mgeier/libflac-sys#18]
See https://github.com/rust-lang/rust-bindgen/issues/1651.

**Comment by dheijl** [comment]
Hi,

I integrated libflac-sys, through [flac-bound](https://github.com/nabijaczleweli/flac-bound), in my little [swyh-rs](https://github.com/dheijl/swyh-rs/) streaming app, and it worked a breeze. But I see that libflac-sys is still at flac 1.3.3.
I cloned libflac-sys and ran bindgen.sh + cargo test and did not notice any errors or warnings, so I suppose the UB warning problem has now solved.
Hence my question: would it be possible to upgrade libflac-sys to flac 1.3.4 now? 
Thanks!

**Comment by mgeier** [comment]
Thanks for reminding me!

The UB issue indeed seems to be fixed, see #22.

However, with flac 1.3.4 there seems to be still an error with Windows (GNU), see #20.

**Comment by dheijl** [comment]
I didn't check the pull requests, so I'll wait until #22 is resolved.

Thanks!

**Comment by mgeier** [comment]
#22 is already resolved, I guess you meant #20?

FLAC releases seem to be quite slow, see https://github.com/xiph/flac/issues/239, you might want to ask over there if there are any plans for a new release that includes the Windows/MinGW fixes.

**Comment by dheijl** [comment]
Thanks for the tip!
